UsersAchievements/Models/User.cs
using System;
using System.ComponentModel.DataAnnotations;
using UsersAchievements.Helpers;

namespace UsersAchievements.Models
{
    public sealed class User
    {
        public Guid Id { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Birthdate]
        public DateTime Birthdate { get; set; }

        public int Age => CalculateAge();

        public string Photo { get; set; }

        public User() { }

        public User(string name, DateTime? birthdate)
        {
            Id = Guid.NewGuid();
            Name = name;
            Birthdate = CheckBirthdate(birthdate);
        }

        public override string ToString()
        {
            return Name;
        }

        public void SetBirthdate(DateTime? birthdate)
        {
            Birthdate = CheckBirthdate(birthdate);
        }

        private int CalculateAge()
        {
            if (Birthdate >= DateTime.Today)
            {
                return 0;
            }

            var zeroTime = new DateTime(1, 1, 1);
            return (zeroTime + (DateTime.Now - Birthdate)).Year - 1;
        }

        private DateTime CheckBirthdate(DateTime? birthdate)
        {
            if (birthdate == null || birthdate > DateTime.Now)
            {
                throw new ArgumentException("Birthdate should be lesser or equal current date", nameof(birthdate));
            }

            return birthdate.Value;
        }
    }
}

UsersAchievements/Controllers/AchievementsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsersAchievements.Models;
using IOFile = System.IO.File;

namespace UsersAchievements.Controllers
{
    public class AchievementsController : Controller
    {
        private List<Achievement> Achievements => AchievementsRepository.Instance.Achievements;

        // GET: Achievements
        public ActionResult Index()
        {
            return View(Achievements);
        }

        // GET: Achievements/Delete
        public ActionResult Delete(Guid id)
        {
            Achievements.Remove(Achievements.Single(a => a.Id == id));
            return RedirectToAction("Index");
        }

        //GET: Achievements/Create
        public ActionResult Create()
        {
            return View();
        }

        //GET: Achievements/Edit
        public ActionResult Edit(Guid id)
        {
            return View(Achievements.Single(a => a.Id == id));
        }

        //POST: Achievements/Create
        [HttpPost]
        public ActionResult Create(Achievement model)
        {
            if (ModelState.IsValid)
            {
                Achievements.Add(model);
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        //POST: Achievements/SaveChanges
        public ActionResult SaveChanges(Guid id, string title, string description, HttpPostedFileBase image, string deleteImage)
        {
            var achievement = Achievements.Single(a => a.Id == id);

            if (image != null)
            {
                achievement.Image = achievement.Id + ".png";
                using (var stream = IOFile.Create(HttpContext.Server.MapPath($"~/Content/Photos/{achievement.Id}.png")))
                {
                    image.InputStream.Seek(0, SeekOrigin.Begin);
                    image.InputStream.CopyTo(stream);
                }
            }

            if (!string.IsNullOrEmpty(deleteImage) && deleteImage == "on")
            {
                achievement.Image = null;
            }

            achievement.Title = title;
            achievement.Description = description;
            return RedirectToAction("Index");
        }
    }
}

UsersAchievements/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using UsersAchievements.Helpers;
using UsersAchievements.Models;
using IOFile = System.IO.File;

namespace UsersAchievements.Controllers
{
    public class UsersController : Controller
    {
        private List<User> Users => UsersRepository.Instance.Users;

        // GET: Users
        public ActionResult Index()
        {
            return View(Users);
        }

        // GET: Users/Delete
        public ActionResult Delete(Guid id)
        {
            Users.Remove(Users.Single(u => u.Id == id));
            return RedirectToAction("Index");
        }


        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Users/Edit
        public ActionResult Edit(Guid id)
        {
            return View(Users.Single(u => u.Id == id));
        }

        // GET: Users/GetUsersList
        public ActionResult GetUsersList()
        {
            var usersString = "";
            foreach (var user in Users)
            {
                usersString += user + Environment.NewLine;
            }

            return File(Encoding.UTF8.GetBytes(usersString), "application/octet-stream", "users_list.txt");
        }

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create([ModelBinder(typeof(UserModelBinder))]User model)
        {
            ModelState.Clear();
            TryValidateModel(model);
            if (ModelState.IsValid)
            {
                Users.Add(model);
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        // POST: Users/SaveChanges
        public ActionResult SaveChanges(Guid id, string name, DateTime? birthdate, HttpPostedFileBase photo, string deletePhoto)
        {
            var user = Users.Single(u => u.Id == id);
            user.Name = name;
            user.SetBirthdate(birthdate);
            if (photo != null)
            {
                user.Photo = user.Id + ".png";
                using (var stream = IOFile.Create(HttpContext.Server.MapPath($"~/Content/Photos/{user.Id}.png")))
                {
                    photo.InputStream.Seek(0, SeekOrigin.Begin);
                    photo.InputStream.CopyTo(stream);
                }
            }

            if (!string.IsNullOrEmpty(deletePhoto) && deletePhoto == "on")
            {
                user.Photo = null;
            }

            return RedirectToAction("Index");
        }
    }
}

UsersAchievements/Views/Users/Create.cshtml
@model User

@{
    ViewBag.Title = "Create user";
    Layout = "~/Views/Users/_UsersLayout.cshtml";
}

@section breadcrumbs
{
    <li class="breadcrumb-item active"><a href="@Url.Action("Create")">Create user</a></li>
}

<h3>@ViewBag.Title</h3>
@{ Html.BeginForm("Create"); }
@Html.ValidationMessageFor(m => m.Name)
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">Full name</span>
    </div>
    @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter name" } })
</div>
@Html.ValidationMessageFor(m => m.Birthdate)
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">Birthdate</span>
    </div>
    @Html.EditorFor(m => m.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
</div>
<button type="submit" class="btn btn-primary">Create</button>
@{ Html.EndForm(); }
<a href="@Url.Action("Index")">Back to users list</a>

UsersAchievements/Views/Users/Edit.cshtml
@model User

@{
    Layout = "~/Views/Users/_UsersLayout.cshtml";
    ViewBag.Title = "Edit user";
}

@section breadcrumbs
{
    <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
}

<h3>@Model</h3>

@{ Html.BeginForm("SaveChanges", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }); }
@Html.Hidden("Id", Model.Id)
@if (!string.IsNullOrEmpty(Model.Photo))
{
    @Html.Label("Photo", "Photo") @Html.Image("/Content/Photos/" + Model.Photo, "User photo")<br />
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="checkbox" name="DeletePhoto" />
            </div>
        </div>
        <div class="input-group-append">
            <span class="input-group-text">Delete photo</span>
        </div>
    </div>
}
else
{
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Photo</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" name="Photo" accept="image/*" id="Photo">
            <label class="custom-file-label" for="Photo">Choose file</label>
        </div>
    </div>
}
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">Full name</span>
    </div>
    <input type="text" class="form-control" name="Name" value="@Model.Name" placeholder="Enter full name" />
</div>
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">Birthdate</span>
    </div>
    <input type="date" class="form-control" name="Birthdate" value="@Model.Birthdate.ToString("yyyy-MM-dd")" />
</div>
<button type="submit" class="btn btn-primary">Save changes</button>
@{ Html.EndForm(); }

UsersAchievements/Views/Users/Index.cshtml
@model List<User>

@{
    Layout = "~/Views/Users/_UsersLayout.cshtml";
    ViewBag.Title = "Users";
}

<table>
    <tr>
        <th>Photo</th>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Age</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@(string.IsNullOrEmpty(user.Photo) ? Html.Image("/Content/Photos/default.png", "User photo") : Html.Image("/Content/Photos/" + user.Photo, "User photo", new Dictionary<string, object> { { "style", "max-height: 100px; max-width: 100px;" } }))</td>
            <td>@user</td>
            <td>@user.Birthdate.ToString("d")</td>
            <td>@user.Age</td>
            <td><a href="@Url.Action("Edit", new { id = user.Id })" class="btn btn-primary" role="button">Edit</a></td>
            <td><a href="@Url.Action("Delete", new { id = user.Id})" class="btn btn-danger">Delete</a></td>
        </tr>
    }
</table>
<a href="@Url.Action("Create")">Create user</a>

UsersAchievements/Views/Users/_UsersLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section navbar
{
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">Users Achievements</a>
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="/">Home</a>
            <a class="nav-item nav-link active" href="@Url.Action("Index")">Users</a>
            <a class="nav-item nav-link" href="@Url.Action("Index", "Achievements")">Achievements</a>
        </div>
    </nav>
}

@section breadcrumbs
{
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="@Url.Action("Index")">Users</a></li>
    @RenderSection("breadcrumbs", false)
}

<h2>Users</h2>

@RenderBody()